dune-foamgrid: Dune::FoamGrid< dimworld > Class Template Reference
Dune::FoamGrid< dimworld > Class Template Reference
An implementation of the Dune grid interface: a 2d simplicial grid in an n-dimensional world.
#include <dune/foamgrid/foamgrid.hh>
Public Types
enum { dimension = 2 }
This grid is always 2-dimensional.
typedef FoamGridFamily< dimworld > GridFamily
type of the used GridFamily for this grid
typedef FoamGridFamily
< dimworld >::Traits Traits
Exports various types belonging to this grid class.
typedef double ctype
The type used to store coordinates.
Public Member Functions
FoamGrid ()
Constructor, constructs an empty grid.
~FoamGrid ()
Destructor.
int maxLevel () const
template<int codim>
Traits::template Codim< codim >
::LevelIterator lbegin (int level) const
Iterator to first entity of given codim on level.
template<int codim>
Traits::template Codim< codim >
::LevelIterator lend (int level) const
one past the end on this level
template<int codim, PartitionIteratorType PiType>
Traits::template Codim< codim >
::template Partition< PiType >
::LevelIterator lbegin (int level) const
Iterator to first entity of given codim on level.
template<int codim, PartitionIteratorType PiType>
Traits::template Codim< codim >
::template Partition< PiType >
::LevelIterator lend (int level) const
one past the end on this level
template<int codim>
Traits::template Codim< codim >
::LeafIterator leafbegin () const
Iterator to first leaf entity of given codim.
template<int codim>
Traits::template Codim< codim >
::LeafIterator leafend () const
one past the end of the sequence of leaf entities
template<int codim, PartitionIteratorType PiType>
Traits::template Codim< codim >
::template Partition< PiType >
::LeafIterator leafbegin () const
Iterator to first leaf entity of given codim.
template<int codim, PartitionIteratorType PiType>
Traits::template Codim< codim >
::template Partition< PiType >
::LeafIterator leafend () const
one past the end of the sequence of leaf entities
int size (int level, int codim) const
Number of grid entities per level and codim.
int size (int codim) const
number of leaf entities per codim in this process
int size (int level, GeometryType type) const
number of entities per level, codim and geometry type in this process
int size (GeometryType type) const
number of leaf entities per codim and geometry type in this process
size_t numBoundarySegments () const
The number of boundary edges on the coarsest level.
const Traits::GlobalIdSet & globalIdSet () const
Access to the GlobalIdSet.
const Traits::LocalIdSet & localIdSet () const
Access to the LocalIdSet.
const Traits::LevelIndexSet & levelIndexSet (int level) const
Access to the LevelIndexSets.
const Traits::LeafIndexSet & leafIndexSet () const
Access to the LeafIndexSet.
Grid Refinement Methods
void globalRefine (int refCount)
bool mark (int refCount, const typename Traits::template Codim< 0 >::EntityPointer &e)
Mark entity for refinement.
int getMark (const typename Traits::template Codim< 0 >::EntityPointer &e) const
Return refinement mark for entity.
bool preAdapt ()
Book-keeping routine to be called before adaptation.
bool adapt ()
Triggers the grid refinement process.
void postAdapt ()
Clean up refinement markers.
Methods for parallel computations
unsigned int overlapSize (int codim) const
Size of the overlap on the leaf level.
unsigned int ghostSize (int codim) const
Size of the ghost cell layer on the leaf level.
unsigned int overlapSize (int level, int codim) const
Size of the overlap on a given level.
unsigned int ghostSize (int level, int codim) const
Size of the ghost cell layer on a given level.
Friends
class FoamGridLevelIndexSet< const FoamGrid >
class FoamGridLeafIndexSet< const FoamGrid >
class FoamGridGlobalIdSet< const FoamGrid >
class FoamGridLocalIdSet< const FoamGrid >
class FoamGridHierarchicIterator< const FoamGrid >
class FoamGridLevelIntersectionIterator< const FoamGrid >
class FoamGridLeafIntersectionIterator< const FoamGrid >
class FoamGridLevelIntersection< const FoamGrid >
class FoamGridLevelIterator
class FoamGridLeafIterator
class GridFactory
class FoamGridEntity
Detailed Description
template<int dimworld>
class Dune::FoamGrid< dimworld >
An implementation of the Dune grid interface: a 2d simplicial grid in an n-dimensional world.
Template Parameters:
dimworld Dimension of the world space
Member Typedef Documentation
template<int dimworld> typedef double Dune::FoamGrid< dimworld >::ctype
The type used to store coordinates.
template<int dimworld> typedef FoamGridFamily<dimworld> Dune::FoamGrid< dimworld >::GridFamily
type of the used GridFamily for this grid
template<int dimworld> typedef FoamGridFamily<dimworld>::Traits Dune::FoamGrid< dimworld >::Traits
Exports various types belonging to this grid class.
Member Enumeration Documentation
template<int dimworld> anonymous enum
This grid is always 2-dimensional.
Enumerator:
dimension
Constructor & Destructor Documentation
template<int dimworld> Dune::FoamGrid< dimworld >::FoamGrid () [inline]
Constructor, constructs an empty grid.
template<int dimworld> Dune::FoamGrid< dimworld >::~FoamGrid () [inline]
Destructor.
Member Function Documentation
template<int dimworld> bool Dune::FoamGrid< dimworld >::adapt () [inline]
Triggers the grid refinement process.
template<int dimworld> int Dune::FoamGrid< dimworld >::getMark (const typename Traits::template Codim< 0 >::EntityPointer & e) const [inline]
Return refinement mark for entity.
Returns:
refinement mark (1,0,-1)
template<int dimworld> unsigned int Dune::FoamGrid< dimworld >::ghostSize (int codim) const [inline]
Size of the ghost cell layer on the leaf level.
template<int dimworld> unsigned int Dune::FoamGrid< dimworld >::ghostSize (int level, int codim) const [inline]
Size of the ghost cell layer on a given level.
template<int dimworld> const Traits::GlobalIdSet& Dune::FoamGrid< dimworld >::globalIdSet () const [inline]
Access to the GlobalIdSet.
template<int dimworld> void Dune::FoamGrid< dimworld >::globalRefine (int refCount) [inline]
global refinement
template<int dimworld> template<int codim, PartitionIteratorType PiType> Traits::template Codim<codim>::template Partition<PiType>::LevelIterator Dune::FoamGrid< dimworld >::lbegin (int level) const [inline]
Iterator to first entity of given codim on level.
References Dune::FoamGrid< dimworld >::dimension, and Dune::FoamGrid< dimworld >::maxLevel().
template<int dimworld> template<int codim> Traits::template Codim<codim>::LevelIterator Dune::FoamGrid< dimworld >::lbegin (int level) const [inline]
Iterator to first entity of given codim on level.
References Dune::FoamGrid< dimworld >::dimension, and Dune::FoamGrid< dimworld >::maxLevel().
template<int dimworld> template<int codim, PartitionIteratorType PiType> Traits::template Codim<codim>::template Partition<PiType>::LeafIterator Dune::FoamGrid< dimworld >::leafbegin () const [inline]
Iterator to first leaf entity of given codim.
template<int dimworld> template<int codim> Traits::template Codim<codim>::LeafIterator Dune::FoamGrid< dimworld >::leafbegin () const [inline]
Iterator to first leaf entity of given codim.
template<int dimworld> template<int codim, PartitionIteratorType PiType> Traits::template Codim<codim>::template Partition<PiType>::LeafIterator Dune::FoamGrid< dimworld >::leafend () const [inline]
one past the end of the sequence of leaf entities
template<int dimworld> template<int codim> Traits::template Codim<codim>::LeafIterator Dune::FoamGrid< dimworld >::leafend () const [inline]
one past the end of the sequence of leaf entities
template<int dimworld> const Traits::LeafIndexSet& Dune::FoamGrid< dimworld >::leafIndexSet () const [inline]
Access to the LeafIndexSet.
Referenced by Dune::FoamGrid< dimworld >::size().
template<int dimworld> template<int codim, PartitionIteratorType PiType> Traits::template Codim<codim>::template Partition<PiType>::LevelIterator Dune::FoamGrid< dimworld >::lend (int level) const [inline]
one past the end on this level
References Dune::FoamGrid< dimworld >::dimension, and Dune::FoamGrid< dimworld >::maxLevel().
template<int dimworld> template<int codim> Traits::template Codim<codim>::LevelIterator Dune::FoamGrid< dimworld >::lend (int level) const [inline]
one past the end on this level
References Dune::FoamGrid< dimworld >::dimension, and Dune::FoamGrid< dimworld >::maxLevel().
template<int dimworld> const Traits::LevelIndexSet& Dune::FoamGrid< dimworld >::levelIndexSet (int level) const [inline]
Access to the LevelIndexSets.
References Dune::FoamGrid< dimworld >::maxLevel().
template<int dimworld> const Traits::LocalIdSet& Dune::FoamGrid< dimworld >::localIdSet () const [inline]
Access to the LocalIdSet.
template<int dimworld> bool Dune::FoamGrid< dimworld >::mark (int refCount, const typename Traits::template Codim< 0 >::EntityPointer & e) [inline]
Mark entity for refinement.
This only works for entities of codim 0. The parameter is currently ignored
Returns:
true, if marking was successful
false, if marking was not possible
Todo:
Why do I need those const_casts here?
template<int dimworld> int Dune::FoamGrid< dimworld >::maxLevel () const [inline]
Return maximum level defined in this grid. Levels are numbered 0 ... maxlevel with 0 the coarsest level.
Referenced by Dune::FoamGrid< dimworld >::lbegin(), Dune::FoamGrid< dimworld >::lend(), and Dune::FoamGrid< dimworld >::levelIndexSet().
template<int dimworld> size_t Dune::FoamGrid< dimworld >::numBoundarySegments () const [inline]
The number of boundary edges on the coarsest level.
template<int dimworld> unsigned int Dune::FoamGrid< dimworld >::overlapSize (int codim) const [inline]
Size of the overlap on the leaf level.
template<int dimworld> unsigned int Dune::FoamGrid< dimworld >::overlapSize (int level, int codim) const [inline]
Size of the overlap on a given level.
template<int dimworld> void Dune::FoamGrid< dimworld >::postAdapt () [inline]
Clean up refinement markers.
template<int dimworld> bool Dune::FoamGrid< dimworld >::preAdapt () [inline]
Book-keeping routine to be called before adaptation.
template<int dimworld> int Dune::FoamGrid< dimworld >::size (GeometryType type) const [inline]
number of leaf entities per codim and geometry type in this process
References Dune::FoamGrid< dimworld >::leafIndexSet().
template<int dimworld> int Dune::FoamGrid< dimworld >::size (int level, GeometryType type) const [inline]
number of entities per level, codim and geometry type in this process
template<int dimworld> int Dune::FoamGrid< dimworld >::size (int level, int codim) const [inline]
Number of grid entities per level and codim.
template<int dimworld> int Dune::FoamGrid< dimworld >::size (int codim) const [inline]
number of leaf entities per codim in this process
References Dune::FoamGrid< dimworld >::leafIndexSet().
Friends And Related Function Documentation
template<int dimworld> friend class FoamGridEntity [friend]
template<int dimworld> friend class FoamGridGlobalIdSet< const FoamGrid > [friend]
template<int dimworld> friend class FoamGridHierarchicIterator< const FoamGrid > [friend]
template<int dimworld> friend class FoamGridLeafIndexSet< const FoamGrid > [friend]
template<int dimworld> friend class FoamGridLeafIntersectionIterator< const FoamGrid > [friend]
template<int dimworld> friend class FoamGridLeafIterator [friend]
template<int dimworld> friend class FoamGridLevelIndexSet< const FoamGrid > [friend]
template<int dimworld> friend class FoamGridLevelIntersection< const FoamGrid > [friend]
template<int dimworld> friend class FoamGridLevelIntersectionIterator< const FoamGrid > [friend]
template<int dimworld> friend class FoamGridLevelIterator [friend]
template<int dimworld> friend class FoamGridLocalIdSet< const FoamGrid > [friend]
template<int dimworld> friend class GridFactory [friend]
The documentation for this class was generated from the following file:
foamgrid.hh