dune-foamgrid: Dune::FoamGridLevelIntersection< GridImp > Class Template Reference
Dune::FoamGridLevelIntersection< GridImp > Class Template Reference
#include <dune/foamgrid/foamgrid/foamgridintersections.hh>
Public Types
typedef GridImp::template
Codim< 0 >::EntityPointer EntityPointer
typedef GridImp::template
Codim< 1 >::Geometry Geometry
typedef GridImp::template
Codim< 1 >::LocalGeometry LocalGeometry
typedef GridImp::template
Codim< 0 >::Entity Entity
typedef Dune::Intersection
< const GridImp,
Dune::FoamGridLevelIntersectionIterator > Intersection
Public Member Functions
FoamGridLevelIntersection (const FoamGridEntityImp< 2, dimworld > *center, int nb)
EntityPointer inside () const
EntityPointer outside () const
bool boundary () const
return true if intersection is with boundary.
bool neighbor () const
return true if across the edge an neighbor on this level exists
int boundaryId () const
return information about the Boundary
int boundarySegmentIndex () const
return information about the Boundary
bool conforming () const
Return true if this is a conforming intersection.
GeometryType type () const
Geometry type of an intersection.
const LocalGeometry & geometryInInside () const
const LocalGeometry & geometryInOutside () const
const Geometry & geometry () const
int indexInInside () const
local number of codim 1 entity in self where intersection is contained in
int indexInOutside () const
local number of codim 1 entity in neighbor where intersection is contained
FieldVector< ctype, dimworld > outerNormal (const FieldVector< ctype, dim-1 > &local) const
return outer normal
FieldVector< ctype, dimworld > integrationOuterNormal (const FieldVector< ctype, dim-1 > &local) const
return outer normal multiplied by the integration element
FieldVector< ctype, dimworld > unitOuterNormal (const FieldVector< ctype, dim-1 > &local) const
return unit outer normal
FieldVector< ctype, dimworld > centerUnitOuterNormal () const
return unit outer normal at the intersection center
Friends
class FoamGridLevelIntersectionIterator< GridImp >
Detailed Description
template<class GridImp>
class Dune::FoamGridLevelIntersection< GridImp >
Todo:
Please doc me !
Member Typedef Documentation
template<class GridImp > typedef GridImp::template Codim<0>::Entity Dune::FoamGridLevelIntersection< GridImp >::Entity
Reimplemented in Dune::FoamGridLeafIntersection< GridImp >.
template<class GridImp > typedef GridImp::template Codim<0>::EntityPointer Dune::FoamGridLevelIntersection< GridImp >::EntityPointer
Reimplemented in Dune::FoamGridLeafIntersection< GridImp >.
template<class GridImp > typedef GridImp::template Codim<1>::Geometry Dune::FoamGridLevelIntersection< GridImp >::Geometry
Reimplemented in Dune::FoamGridLeafIntersection< GridImp >.
template<class GridImp > typedef Dune::Intersection<const GridImp, Dune::FoamGridLevelIntersectionIterator> Dune::FoamGridLevelIntersection< GridImp >::Intersection
Reimplemented in Dune::FoamGridLeafIntersection< GridImp >.
template<class GridImp > typedef GridImp::template Codim<1>::LocalGeometry Dune::FoamGridLevelIntersection< GridImp >::LocalGeometry
Reimplemented in Dune::FoamGridLeafIntersection< GridImp >.
Constructor & Destructor Documentation
template<class GridImp > Dune::FoamGridLevelIntersection< GridImp >::FoamGridLevelIntersection (const FoamGridEntityImp< 2, dimworld > * center, int nb) [inline]
Member Function Documentation
template<class GridImp > bool Dune::FoamGridLevelIntersection< GridImp >::boundary () const [inline]
return true if intersection is with boundary.
References Dune::FoamGridEntityImp< 2, dimworld >::edges_.
template<class GridImp > int Dune::FoamGridLevelIntersection< GridImp >::boundaryId () const [inline]
return information about the Boundary
Deprecated:
References Dune::FoamGridEntityImp< 2, dimworld >::edges_.
template<class GridImp > int Dune::FoamGridLevelIntersection< GridImp >::boundarySegmentIndex () const [inline]
return information about the Boundary
References Dune::FoamGridEntityImp< 2, dimworld >::edges_.
template<class GridImp > FieldVector<ctype, dimworld> Dune::FoamGridLevelIntersection< GridImp >::centerUnitOuterNormal () const [inline]
return unit outer normal at the intersection center
References Dune::FoamGridLevelIntersection< GridImp >::outerNormal().
template<class GridImp > bool Dune::FoamGridLevelIntersection< GridImp >::conforming () const [inline]
Return true if this is a conforming intersection.
template<class GridImp > const Geometry& Dune::FoamGridLevelIntersection< GridImp >::geometry () const [inline]
intersection of codimension 1 of this neighbor with element where iteration started. Here returned element is in GLOBAL coordinates of the element where iteration started.
References Dune::FoamGridEntityImp< 0, dimworld >::pos_, Dune::FoamGridLevelIntersection< GridImp >::type(), Dune::FoamGridEntityImp< 2, dimworld >::type(), and Dune::FoamGridEntityImp< 2, dimworld >::vertex_.
template<class GridImp > const LocalGeometry& Dune::FoamGridLevelIntersection< GridImp >::geometryInInside () const [inline]
intersection of codimension 1 of this neighbor with element where iteration started. Here returned element is in LOCAL coordinates of the element where iteration started.
References Dune::FoamGridLevelIntersection< GridImp >::type(), and Dune::FoamGridEntityImp< 2, dimworld >::type().
template<class GridImp > const LocalGeometry& Dune::FoamGridLevelIntersection< GridImp >::geometryInOutside () const [inline]
intersection of codimension 1 of this neighbor with element where iteration started. Here returned element is in LOCAL coordinates of neighbor
References Dune::FoamGridEntityImp< 2, dimworld >::edges_, Dune::FoamGridLevelIntersection< GridImp >::indexInOutside(), Dune::FoamGridLevelIntersection< GridImp >::outside(), Dune::FoamGridLevelIntersection< GridImp >::type(), and Dune::FoamGridEntityImp< 2, dimworld >::type().
template<class GridImp > int Dune::FoamGridLevelIntersection< GridImp >::indexInInside () const [inline]
local number of codim 1 entity in self where intersection is contained in
template<class GridImp > int Dune::FoamGridLevelIntersection< GridImp >::indexInOutside () const [inline]
local number of codim 1 entity in neighbor where intersection is contained
References Dune::FoamGridEntityImp< 2, dimworld >::edges_.
Referenced by Dune::FoamGridLevelIntersection< GridImp >::geometryInOutside().
template<class GridImp > EntityPointer Dune::FoamGridLevelIntersection< GridImp >::inside () const [inline]
return EntityPointer to the Entity on the inside of this intersection (that is the Entity where we started this Iterator)
template<class GridImp > FieldVector<ctype, dimworld> Dune::FoamGridLevelIntersection< GridImp >::integrationOuterNormal (const FieldVector< ctype, dim-1 > & local) const [inline]
return outer normal multiplied by the integration element
References Dune::FoamGridEntityImp< 0, dimworld >::pos_, Dune::FoamGridEntityImp< 2, dimworld >::type(), Dune::FoamGridLevelIntersection< GridImp >::unitOuterNormal(), and Dune::FoamGridEntityImp< 2, dimworld >::vertex_.
template<class GridImp > bool Dune::FoamGridLevelIntersection< GridImp >::neighbor () const [inline]
return true if across the edge an neighbor on this level exists
References Dune::FoamGridEntityImp< 2, dimworld >::edges_.
template<class GridImp > FieldVector<ctype, dimworld> Dune::FoamGridLevelIntersection< GridImp >::outerNormal (const FieldVector< ctype, dim-1 > & local) const [inline]
return outer normal
References Dune::FoamGridEntityImp< 0, dimworld >::pos_, Dune::FoamGridEntityImp< 2, dimworld >::type(), and Dune::FoamGridEntityImp< 2, dimworld >::vertex_.
Referenced by Dune::FoamGridLevelIntersection< GridImp >::centerUnitOuterNormal(), and Dune::FoamGridLevelIntersection< GridImp >::unitOuterNormal().
template<class GridImp > EntityPointer Dune::FoamGridLevelIntersection< GridImp >::outside () const [inline]
return EntityPointer to the Entity on the outside of this intersection (that is the neighboring Entity)
References Dune::FoamGridEntityImp< 2, dimworld >::edges_.
Referenced by Dune::FoamGridLevelIntersection< GridImp >::geometryInOutside().
template<class GridImp > GeometryType Dune::FoamGridLevelIntersection< GridImp >::type () const [inline]
Geometry type of an intersection.
Referenced by Dune::FoamGridLevelIntersection< GridImp >::geometry(), Dune::FoamGridLevelIntersection< GridImp >::geometryInInside(), and Dune::FoamGridLevelIntersection< GridImp >::geometryInOutside().
template<class GridImp > FieldVector<ctype, dimworld> Dune::FoamGridLevelIntersection< GridImp >::unitOuterNormal (const FieldVector< ctype, dim-1 > & local) const [inline]
return unit outer normal
References Dune::FoamGridLevelIntersection< GridImp >::outerNormal().
Referenced by Dune::FoamGridLevelIntersection< GridImp >::integrationOuterNormal().
Friends And Related Function Documentation
template<class GridImp > friend class FoamGridLevelIntersectionIterator< GridImp > [friend]
The documentation for this class was generated from the following file:
foamgridintersections.hh