// Copyright (C) 2009-2010 Matthias Messner, Michael Messner, Franz
// Rammerstorfer, Peter Urthaler
// 
// This file is part of HyENA - a C++ boundary element methods library.
// 
// HyENA is free software: you can redistribute it and/or modify it under the
// terms of the GNU Lesser Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
// 
// HyENA is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE.  See the GNU Lesser Public License for more
// details.
// 
// You should have received a copy of the GNU Lesser Public License along with
// HyENA. If not, see <http://www.gnu.org/licenses/>.

/**
 * @file   traits.H
 * @ingroup traits
 *
 * If you want to include all Hyena traits at once, you can do: 
 * \code
 * #include "common/traits.H"
 * \endcode
 *     
 * @author Rf
 * @date   created:     09.12.09
 *         last change: 09.12.09
 */
#ifndef traits_h
#define traits_h



//#include "common/pdetraits.H"
#include "shapetraits.H"
//#include "common/approxtraits.H"
//#include "common/numbertraits.H"
//#include "common/scalartraits.H"
//#include "common/singularitytraits.H"
//#include "common/doftraits.H"
//#include "triatraits.H"


#endif
