# Check to see whether armadillo was compiled with LAPACK and BLAS
if(NOT ARMADILLO_INCLUDE_DIR)
    return()
endif()
include(CheckSymbolExists)
set(CMAKE_REQUIRED_INCLUDE ${ARMADILLO_INCLUDE_DIR})
check_symbol_exists(ARMA_USE_LAPACK
    "${ARMADILLO_INCLUDE_DIR}/armadillo" has_lapack)
check_symbol_exists(ARMA_USE_BLAS
    "${ARMADILLO_INCLUDE_DIR}/armadillo" has_blas)
set(ARMADILLO_CXX_FLAGS)
if(NOT has_lapack OR NOT has_blas)
    set(ARMADILLO_CXX_FLAGS "${ARMADILLO_CXX_FLAGS} -DARMA_DONT_USE_WRAPPER")
endif()
if(NOT has_lapack)
    set(ARMADILLO_CXX_FLAGS "${ARMADILLO_CXX_FLAGS} -DARMA_USE_LAPACK")
endif()
if(NOT has_blas)
    set(ARMADILLO_CXX_FLAGS "${ARMADILLO_CXX_FLAGS} -DARMA_USE_BLAS")
endif()
if(NOT "${ARMADILLO_CXX_FLAGS}" STREQUAL "")
    add_definitions(${ARMADILLO_CXX_FLAGS})
endif()
